### PR TITLE
Render add

### PR DESCRIPTION
**Pull request by duckietm**
- SnowStormOnStageEndingEvent and SnowStormOnStageEndingComposer added
- VotePollCounterMessageComposer added
- GuideAdvertisementReadMessageComposer added
- CitizenshipVipOfferPromoEnabledEvent added
- OfferRewardDeliveredMessageEvent added
- RestoreClientMessageEvent added
- FireworkChargeDataEvent added
- CameraSnapshotMessageEvent added
- RoomPollResultEvent added
- StartRoomPollEvent added
duckietm committed 27 minutes ago

### CODE REVIEW

**Comment by Gurkengewuerz** [comment]
Thanks for your PR. There are still some errors. Did you test it with `npx nx serve frontend`?
i.e. `libs\renderer\src\nitro\session\handler\PollHandler.ts: SyntaxError: Identifier 'RoomPollResultEvent' has already been declared.` or `libs\renderer\src\nitro\communication\NitroMessages.ts: SyntaxError: Identifier 'GetRecyclerStatusMessageComposer' has already been declared.`.

Also please pull the upstream to update your `.prettierrc` and run `npx prettier --write .` to use the formatting of the repository.

**Comment by duckietm** [comment]
Okie, let me check ;)

**Comment by duckietm** [comment]
Fixed ;)

**Comment by Gurkengewuerz** [comment]
> Fixed ;)

next time please use `npx prettier --write .` for your formatting. I've updated it and pushed to this pr for you.
VSCode with the prettier extension is a must have.

**Pull request merged**
